/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as EvacuationRouteImport } from './routes/evacuation'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RiskMapRouteImport } from './routes/risk-map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const EvacuationRoute = EvacuationRouteImport.update({
  id: '/evacuation',
  path: '/evacuation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMapRoute = RiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/emergency': typeof EmergencyRoute
  '/evacuation': typeof EvacuationRoute
  '/planner': typeof PlannerRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/risk-map': typeof RiskMapRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/emergency': typeof EmergencyRoute
  '/evacuation': typeof EvacuationRoute
  '/planner': typeof PlannerRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/risk-map': typeof RiskMapRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/emergency': typeof EmergencyRoute
  '/evacuation': typeof EvacuationRoute
  '/planner': typeof PlannerRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/risk-map': typeof RiskMapRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/emergency'
    | '/evacuation'
    | '/planner'
    | '/reports'
    | '/resources'
    | '/risk-map'
    | '/settings'
    | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/emergency'
    | '/evacuation'
    | '/planner'
    | '/reports'
    | '/resources'
    | '/risk-map'
    | '/settings'
    | '/simulator'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/emergency'
    | '/evacuation'
    | '/planner'
    | '/reports'
    | '/resources'
    | '/risk-map'
    | '/settings'
    | '/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  EmergencyRoute: typeof EmergencyRoute
  EvacuationRoute: typeof EvacuationRoute
  PlannerRoute: typeof PlannerRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  RiskMapRoute: typeof RiskMapRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evacuation': {
      id: '/evacuation'
      path: '/evacuation'
      fullPath: '/evacuation'
      preLoaderRoute: typeof EvacuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-map': {
      id: '/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof RiskMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  EmergencyRoute: EmergencyRoute,
  EvacuationRoute: EvacuationRoute,
  PlannerRoute: PlannerRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  RiskMapRoute: RiskMapRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
